[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3.11 -m venv .venv",
  "source .venv/bin/activate",
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "source .venv/bin/activate",
  "python -c 'import sys; print(f\"Python version: {sys.version}\")'"
]

[start]
cmd = "source .venv/bin/activate && python main.py"
